/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tm.mouctar.View;

import com.tm.mouctar.encoder.EncodeToCard;

import javax.smartcardio.*;
import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author UCAD-DISI
 */
public class FenetreMain extends JFrame
{

    private static JFrame popup = null;

    /**
     * Creates new form FenetreMain
     */
    public FenetreMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        window = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        windowEtudiant = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        windowPersonnel = new javax.swing.JPanel();
        windowVisiteur = new javax.swing.JPanel();
        refreshBtn = new javax.swing.JButton();
        lectuers = new javax.swing.JComboBox<>();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 620));

        mainLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mainLabel.setText("Bienvenue sur SpringCard App");

        window.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1516, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );

        window.addTab("Menu", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestion des étudiants");

        javax.swing.GroupLayout windowEtudiantLayout = new javax.swing.GroupLayout(windowEtudiant);
        windowEtudiant.setLayout(windowEtudiantLayout);
        windowEtudiantLayout.setHorizontalGroup(
            windowEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowEtudiantLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1107, Short.MAX_VALUE))
        );
        windowEtudiantLayout.setVerticalGroup(
            windowEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(windowEtudiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );

        window.addTab("Etudiant", windowEtudiant);

        javax.swing.GroupLayout windowPersonnelLayout = new javax.swing.GroupLayout(windowPersonnel);
        windowPersonnel.setLayout(windowPersonnelLayout);
        windowPersonnelLayout.setHorizontalGroup(
            windowPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1516, Short.MAX_VALUE)
        );
        windowPersonnelLayout.setVerticalGroup(
            windowPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );

        window.addTab("Personnel", windowPersonnel);

        javax.swing.GroupLayout windowVisiteurLayout = new javax.swing.GroupLayout(windowVisiteur);
        windowVisiteur.setLayout(windowVisiteurLayout);
        windowVisiteurLayout.setHorizontalGroup(
            windowVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1516, Short.MAX_VALUE)
        );
        windowVisiteurLayout.setVerticalGroup(
            windowVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );

        window.addTab("Visiteur", windowVisiteur);

        refreshBtn.setText("Raffrechir la selection");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        lectuers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection de lecteur" }));
        lectuers.setAutoscrolls(true);
        lectuers.setMaximumSize(new java.awt.Dimension(234, 234));
        lectuers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectuersActionPerformed(evt);
            }
        });

        message.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        message.setForeground(new java.awt.Color(255, 0, 51));
        message.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lectuers, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(mainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(window)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lectuers, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        try {
            for (CardTerminal c : EncodeToCard.getCardTerminals()){
                lectuers.addItem(c.getName());
            }
        } catch (CardException | ArrayIndexOutOfBoundsException e){
            message.setText("Impossible de selectionné ce lecteur.");
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void lectuersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectuersActionPerformed
        try {
            EncodeToCard.setCardTerminal(lectuers.getSelectedIndex() - 1);
        } catch (CardException e){
            message.setText("Il y'a eu un problème lors de la selection de l'imprimante.");
        }
    }//GEN-LAST:event_lectuersActionPerformed

    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException |
                 IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lectuers;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel message;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTabbedPane window;
    private javax.swing.JPanel windowEtudiant;
    private javax.swing.JPanel windowPersonnel;
    private javax.swing.JPanel windowVisiteur;
    // End of variables declaration//GEN-END:variables
}
